In [6]:
# 별칭을 tf으로 하는것이 일반적
import tensorflow as tf
# print(tf.__version__)

In [42]:
# 거의 대부분 우리가 직접 tensor(텐서)를 생성하는 경우는 없다.
# Tensorflow가 tf.io나 tf.data라는 모듈을 기본적으로 가지고 있어서,
# 데이터를 가져와서 자동으로 tensor로 전환(변환)을 해준다.
# 이 변환된 텐서를 나중에 neural network(신경망)에서 사용한다.

# tensorflow에서 사용하는 상수 (constant)
scala = tf.constant(7)
scala

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# ramdom (임의의) tensor를 생성
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

#### 지금과 같이 랜덤인데 값이 같은 상황을 Pseudorandom
### [Pseudorandom](https://www.computerhope.com/jargon/p/pseudo-random.htm)

In [13]:
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
# ramdom (임의의) tensor를 생성
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))



[tensorflow random number API를 설명한 웹페이지](https://www.tensorflow.org/guide/random_numbers?hl=ko)

In [18]:
random_3, random_4, random_3 == random_4


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [19]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
not_shuffled.ndim

2

In [41]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [74]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>


[set_seed 설명 웹페이지](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [75]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [77]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [80]:
tf.ones(shape=(3,2,3))


<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [81]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## tensor의 형태와 numpy array의 형식이 같다.
### tensor는 GPU에서 실행이 가능하다.

### 행렬이나 텐서는 대문자로 이름을 표기하고
### 벡터는 소문자로 이름 표기

In [83]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) 
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [86]:
tensor_A = tf.constant(numpy_A, shape=(2,4,3))

In [87]:
tensor_A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

## tensor (텐서)에서 정보를 얻어오기
* Shape : 텐서의 차원에 존재하는 값들의 개수
* Rank : 텐서 차원의 수, scala는 rank=0, vector는 rank=1, matrix는 rank=2, tensor rank=n
* Axis : Rank와 같다.
* Dimension : Rank와 같다.
* Size : tensor에 존재하는 값들의 개수

In [96]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [95]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [106]:
print("텐서에 존재하는 자료 값들의 자료형 : ", rank_4_tensor.dtype)
print("텐서에 차원(rank) : ", rank_4_tensor.ndim)
print("텐서에 형태 : ", rank_4_tensor.shape)

print("텐서의 0번째 axis : ", rank_4_tensor.shape[0])
print("텐서의 마지막 axis : ", rank_4_tensor.shape[-1])
print("텐서의 모든 값들의 갯수 : ", tf.size(rank_4_tensor).numpy())


텐서에 존재하는 자료 값들의 자료형 :  <dtype: 'float32'>
텐서에 차원(rank) :  4
텐서에 형태 :  (2, 3, 4, 5)
텐서의 0번째 axis :  2
텐서의 마지막 axis :  5
텐서의 모든 값들의 갯수 :  120


In [105]:
type(tf.size(rank_4_tensor)), type(tf.size(rank_4_tensor).numpy())

(tensorflow.python.framework.ops.EagerTensor, numpy.int32)

In [ ]:
# numpy array -> tensor 변환가능
# tensor -> numpy array 변환가능

In [107]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [112]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>