In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np

In [7]:
print(tf.config.list_physical_devices('GPU'))

[]


In [42]:
H = tf.constant(np.arange(1,10))

In [43]:
H.ndim

1

In [44]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [47]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [45]:
H = tf.cast(H, dtype=tf.float32)

In [46]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [6]:
tf.math.log(H)

<tf.Tensor: shape=(1, 9), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246]], dtype=float32)>

In [8]:
# tf.square() : 텐서에 존재하는 모든 값들의 제곱을 계산
# tf.sqrt() : 텐서에 존재하는 모든 값들의 제곱근을 계산
# tf.math.log() : 텐서에 존재하는 모든 값들의 자연로드 (nature log) 계산


In [21]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

[dot](http://matrixmultiplication.xyz/)

In [22]:
# tf.constant : 일반적인 프로그래밍 언어의 상수의 개념 : immutable 즉, 변경할 수 없는 값
# tf.Variable : 일반적인 프로그래밍 언어의 변수 개념 : mutable 즉, 변경할 수 있는 값

In [23]:
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [24]:
I


<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [25]:
I + 10

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [26]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [29]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [30]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [35]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [36]:
# tensor <==> numpy array
# np.array() : tensor를 전달해서 ndarray로 변환 (ndarray는 Numpy의 기본 자료형)
# tensor.numpy() : 텐서 자체에 호출해서 ndarray로 변환
# tensor는 기본자료형: float32
# numpy array의 기본자료형 : float64

In [37]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [39]:
def function(x, y):
    return x**2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x,y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# @tf.function이라는 decorator : 함수를 변경하는 방법
# @tf.function decorator는 function을 callable tensorflow graph로 바꿔준다.
# @tf.function을 통해 선언한 함수는 tensorflow 내부적으로 메모리 효율적 및 실행 최적화를 만들어준다!

In [41]:
@tf.function 
def function2(a, b):
    return a**2 + b

a = tf.constant(np.arange(0, 10))
b = tf.constant(np.arange(10, 20))
function2(a, b)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>