In [1]:
import tensorflow as tf


In [2]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [11]:
# 각 행의 마지막 열의 값을 가져오기
print(rank_2_tensor[:, -1])

tf.Tensor([7 4], shape=(2,), dtype=int32)


In [15]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

# 파이썬에서는 ...은 모든 차원이라는 뜻(모든 것을 의미). rank_2_tensor에 존재하는 모든 것

In [13]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [14]:
rank_2_tensor.ndim, rank_3_tensor.ndim


(2, 3)

In [16]:
rank_3_tensor = rank_2_tensor[tf.newaxis, ...]

In [17]:
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [18]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1의 의미는 파이썬에서 마지막이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [20]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [23]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

## tensor 사칙연산
[Tensorflow의 연산](https://www.tensorflow.org/api_docs/python/tf/math/)

In [24]:

tensor = tf.constant([
    [10, 7], 
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [25]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [26]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [27]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [28]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [32]:
tensor/5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [29]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [30]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [31]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [34]:
tf.divide(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

## 머신 러닝 알고리즘에서 가장많이 사용하는 연산 중에 하나 행렬 연산
[참고:행렬 연산](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
### tensorflow에서는 tf.matmul() 메소드로 matrix multiplication을 구현해 놓았다.
    - matrix multiplication을 실행할 때 꼭 기억해야 할 것이 2개 있다.
        1. 각 행렬을 곱할때(multiplication) 안에 있는 차원은 같아야 한다.
            - (3, 5)@(3, 5) : 행렬 연산이 안됌
            - (5, 3)@(3, 5) : 행렬 연산이 가능
            - (3, 5)@(5, 3) : 가능
        2. 행렬 연산의 결과 행렬의 크기는 바깥의 차원과 같다.
            - (5, 3)@(3, 5) -> (5, 5)
            - (3, 5)@(5, 3) -> (3, 3)
    

In [37]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
X = tf.constant([
    [1,2],
    [3,4],
    [5,6]
])

Y = tf.constant([
    [7,8],
    [9,10],
    [11,12]
])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [42]:
X@Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [44]:
# X, Y는 현재 shape가 (3,2)
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [45]:
# 위의 경우에 matrix multiplication을 하려면
# 1. X의 shape를 (2, 3)으로 바꿔주거나 (2, 3)@(3, 2)
# 2. Y의 shape를 (2, 3)으로 바꿔 줘야한다. (3, 2)@(2, 3)

In [46]:
# tf.reshape() : 텐서의 shape를 우리가 정의한 shape로 변경해 주는 메서드
# tf.transpose() : 주어진 행렬의 행과 열을 바꿔주는 메서드

NameError: name '드' is not defined

In [48]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [50]:
X@tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [53]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [54]:
tf.transpose(X)@Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [55]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [57]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [58]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [59]:
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
Y.shape, tf.reshape(Y, (2,3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [62]:
Y, tf.reshape(Y, (2,3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [63]:
# 16-비트 floating precision vs 32-비트 floating precision
# 낮은 precision이 모바일 장치와 같은 컴퓨팅이나 메모리가 작을 경우에 유용

In [66]:
B = tf.constant([
    [1.7, 7.4]
])

C = tf.constant([
    [1, 7]
])

B, C

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.7, 7.4]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 7]], dtype=int32)>)

In [68]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.7, 7.4]], dtype=float16)>

In [70]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 7.]], dtype=float32)>

In [71]:
# 절대값 구하기
D = tf.constant([
    [-7, -10]
])
D

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ -7, -10]], dtype=int32)>

In [72]:
tf.abs(D)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 10]], dtype=int32)>

In [73]:
# aggregation 함수 사용하기 (min, max, mean, sum)
# tf.reduce_min()
# tf.reduce_max()
# tf.reduce_mean()
# tf.reduce_sum()


In [79]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 67, 89, 40, 33, 57, 42, 91, 20, 96, 67,  4, 23, 77, 42, 99, 62,
       88, 36, 15, 22, 71, 25, 66, 58, 83, 29, 15, 63,  1, 96, 26, 14, 95,
       34, 34, 97, 78, 50, 34,  8, 50, 39, 74, 94, 20, 53, 18, 38, 62])>

In [81]:
tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [82]:
tf.reduce_max(E)


<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [83]:
tf.reduce_mean(E)


<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [85]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2539>

In [89]:
F = tf.constant(np.random.random(50)) # 디폴트가 0~1값을 랜덤으로 만들어 준다.
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.39325137, 0.70027026, 0.9844999 , 0.51075438, 0.56183446,
       0.37011454, 0.22223084, 0.10605106, 0.64282714, 0.89317552,
       0.95913315, 0.86335658, 0.89522644, 0.44584362, 0.48524911,
       0.84747146, 0.79298588, 0.24198468, 0.25897055, 0.07890968,
       0.47646983, 0.40871861, 0.69894924, 0.45484124, 0.37003745,
       0.01207766, 0.06653269, 0.32774527, 0.51523673, 0.14078913,
       0.01559911, 0.44586221, 0.8702048 , 0.43339949, 0.15764571,
       0.42485674, 0.28279824, 0.89394447, 0.93829612, 0.16822471,
       0.78965721, 0.13636106, 0.59662453, 0.02696032, 0.06496075,
       0.14525855, 0.25402149, 0.86982877, 0.80359217, 0.56336169])>

In [90]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [91]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [104]:
print("F에서의 최대 값의 위치 : ", tf.argmax(F).numpy())
print("F에서의 최대값 :", tf.reduce_max(F).numpy())
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 :", F[tf.argmax(F)].numpy())
print("F에서의 최소값의 위치 : ", tf.argmin(F).numpy())
print("F에서의 최소값 :", tf.argmin(F).numpy())
print("F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값을 같은가? :", F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy())


F에서의 최대 값의 위치 :  2
F에서의 최대값 : 0.9844998972477084
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값 : 0.9844998972477084
F에서의 최소값의 위치 :  25
F에서의 최소값 : 25
F에서의 최대값의 위치를 인덱스로 해서 찾은 최대값과 F에서의 최대값을 같은가? : True


In [107]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1,1,1,1,50))
G.shape, G.ndim, G

(TensorShape([1, 1, 1, 1, 50]),
 5,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
 array([[[[[19, 82, 37, 73, 56, 77, 23, 64, 84, 26,  0, 81, 43, 68, 50,
            65, 66, 23,  0, 63, 35, 70, 21, 35,  6, 75, 98, 60, 73, 51,
            95, 98, 99, 70, 69, 75, 69, 57, 43, 85, 44, 34,  1, 94, 56,
            90,  3, 22, 70,  2]]]]])>)

In [106]:
# 1차원 벡터로 변경
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim, G_squeezed

(TensorShape([50]),
 1,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([47, 85, 35, 37, 89, 57, 82, 39, 15, 77, 80, 24,  3, 73, 53, 51, 58,
        94, 52, 40, 90, 76, 74, 41, 49, 11, 23, 95, 80, 61,  9, 99, 42, 77,
        52, 56, 45, 58, 73,  5, 77, 78,  9, 50, 40, 93, 76, 57, 48, 28])>)

In [109]:
# one-hot encoding
list_example = [0, 1, 2, 3]

tf.one_hot(list_example, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [110]:
tf.one_hot(list_example, depth=4, on_value="On", off_value="off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'off', b'off', b'off'],
       [b'off', b'On', b'off', b'off'],
       [b'off', b'off', b'On', b'off'],
       [b'off', b'off', b'off', b'On']], dtype=object)>