## autograd_study.ipynb

In [1]:
import torch

In [2]:
x = torch.tensor([5], dtype=torch.float32, requires_grad=True)
y = torch.tensor([6], dtype=torch.float32, requires_grad=True)

In [3]:
x, y

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [4]:
z = ((x**2) * y) + (x * y)
z

tensor([180.], grad_fn=<AddBackward0>)

In [5]:
total = torch.sum(z)
total

tensor(180., grad_fn=<SumBackward0>)

In [6]:
total.backward()
print(x.grad)

tensor([66.])


In [7]:
print(y.grad)

tensor([30.])


In [8]:
x = torch.randn(10)
x

tensor([ 1.4005,  0.4941, -1.6060,  1.2606, -0.3673,  1.7121,  0.7226, -1.0368,
        -0.7254,  0.4392])

In [9]:
y = 1.8*x + 32 # y = wx + b
y

tensor([34.5209, 32.8894, 29.1092, 34.2690, 31.3388, 35.0817, 33.3007, 30.1338,
        30.6943, 32.7905])

In [11]:
w = torch.ones(1, requires_grad=True)
w

tensor([1.], requires_grad=True)

In [12]:
b = torch.ones(1, requires_grad=True)
b

tensor([1.], requires_grad=True)

In [13]:
y_hat = w * x + b
y_hat 

tensor([ 2.4005,  1.4941, -0.6060,  2.2606,  0.6327,  2.7121,  1.7226, -0.0368,
         0.2746,  1.4392], grad_fn=<AddBackward0>)

In [14]:
loss = torch.sum((y_hat - y)**2)
loss

tensor(9731.2822, grad_fn=<SumBackward0>)

In [15]:
loss.backward()

In [16]:
print(w.grad, b.grad)

tensor([-161.0070]) tensor([-623.6696])


In [17]:
w, w.grad

(tensor([1.], requires_grad=True), tensor([-161.0070]))

In [18]:
x = torch.randint(-100, 100, (100, ), dtype=torch.float32)
x

tensor([ 70., -71.,  24., -34.,  41., -30.,  28., -83.,  32., -92.,  93.,  12.,
         19., -24.,  64.,  73.,   8.,  -2., -63.,  30.,  -2.,  50., -74.,   9.,
         88., -49., -23.,  46., -38., -12., -57., -87.,  84., -18., -27., -28.,
        -41.,  88., -26., -11., -98.,  60., -17., -36., -95.,  61., -34.,  39.,
         45., -72., -84.,   9.,  85.,  74.,  98.,  93.,  62.,  72., -18., -86.,
         98., -80.,  28.,   4., -34., -27., -64.,  57.,  18., -30.,  39.,  -6.,
         98., -36.,  77.,  16.,  87., -32., -68.,  80.,  81.,   6., -38.,  72.,
        -18.,  22., -86.,  12., -45., -51., -62.,  93.,  -6., -44., -63.,  43.,
         87.,  60.,  94., -54.])

In [19]:
y = (1.8 * x) + 32
y

tensor([ 158.0000,  -95.8000,   75.2000,  -29.2000,  105.8000,  -22.0000,
          82.4000, -117.4000,   89.6000, -133.6000,  199.4000,   53.6000,
          66.2000,  -11.2000,  147.2000,  163.4000,   46.4000,   28.4000,
         -81.4000,   86.0000,   28.4000,  122.0000, -101.2000,   48.2000,
         190.4000,  -56.2000,   -9.4000,  114.8000,  -36.4000,   10.4000,
         -70.6000, -124.6000,  183.2000,   -0.4000,  -16.6000,  -18.4000,
         -41.8000,  190.4000,  -14.8000,   12.2000, -144.4000,  140.0000,
           1.4000,  -32.8000, -139.0000,  141.8000,  -29.2000,  102.2000,
         113.0000,  -97.6000, -119.2000,   48.2000,  185.0000,  165.2000,
         208.4000,  199.4000,  143.6000,  161.6000,   -0.4000, -122.8000,
         208.4000, -112.0000,   82.4000,   39.2000,  -29.2000,  -16.6000,
         -83.2000,  134.6000,   64.4000,  -22.0000,  102.2000,   21.2000,
         208.4000,  -32.8000,  170.6000,   60.8000,  188.6000,  -25.6000,
         -90.4000,  176.0000,  177.800

In [20]:
# 가중치
w = torch.ones(1, requires_grad=True)
b = torch.ones(1, requires_grad=True)
y_hat = (w*x) + b # predict value
y_hat

tensor([ 71., -70.,  25., -33.,  42., -29.,  29., -82.,  33., -91.,  94.,  13.,
         20., -23.,  65.,  74.,   9.,  -1., -62.,  31.,  -1.,  51., -73.,  10.,
         89., -48., -22.,  47., -37., -11., -56., -86.,  85., -17., -26., -27.,
        -40.,  89., -25., -10., -97.,  61., -16., -35., -94.,  62., -33.,  40.,
         46., -71., -83.,  10.,  86.,  75.,  99.,  94.,  63.,  73., -17., -85.,
         99., -79.,  29.,   5., -33., -26., -63.,  58.,  19., -29.,  40.,  -5.,
         99., -35.,  78.,  17.,  88., -31., -67.,  81.,  82.,   7., -37.,  73.,
        -17.,  23., -85.,  13., -44., -50., -61.,  94.,  -5., -43., -62.,  44.,
         88.,  61.,  95., -53.], grad_fn=<AddBackward0>)

In [21]:
epochs = 10000
lr = 0.000001

In [23]:
for i in range(epochs):
    loss = torch.sum( (y_hat - y)**2 )
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

        w.grad.zero_()
        b.grad.zero_()

    y_hat = (w*x) + b
print(w.item(), b.item())

1.8057423830032349 27.753883361816406


In [25]:
x = torch.tensor([5], dtype=torch.float32, requires_grad=True)
y = torch.tensor([6], dtype=torch.float32, requires_grad=True)
print(x, y)

tensor([5.], requires_grad=True) tensor([6.], requires_grad=True)


In [27]:
z = ((x**2)*y) + (x*y)
print(z)

tensor([180.], grad_fn=<AddBackward0>)


In [28]:
z.backward()

In [29]:
x.grad

tensor([66.])

In [30]:
y.grad

tensor([30.])