## cnn_cifar10.ipynb

In [11]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [12]:
import torchvision # tensorflow datasets

In [13]:
trainset = torchvision.datasets.CIFAR10(
    root = "./data",
    train = True,
    download= True,
    transform = torchvision.transforms.ToTensor()
)

Files already downloaded and verified


In [14]:
classes = (
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck"
)

In [15]:
type(trainset)

torchvision.datasets.cifar.CIFAR10

In [16]:
trainloader = torch.utils.data.DataLoader(trainset)

In [17]:
type(trainloader)

torch.utils.data.dataloader.DataLoader

In [18]:
data_iter = iter(trainloader)
type(data_iter)

torch.utils.data.dataloader._SingleProcessDataLoaderIter

In [19]:
images, labels = data_iter.next()
print(images.shape)
print(labels.item())

torch.Size([1, 3, 32, 32])
6


In [20]:
# (1, 3, 32, 32)
# 1 : Batch Size
# 3 : channel in input
# 32, 32 : image의 크기

In [21]:
classes[labels.item()]

'frog'

In [22]:
trainloader = torch.utils.data.DataLoader(
    trainset,
    batch_size = 4,
    shuffle = True
)

data_iter = iter(trainloader)
images, labels = data_iter.next()
print(images.shape)

torch.Size([4, 3, 32, 32])


In [23]:
labels

tensor([7, 4, 5, 8])

In [24]:
image_data = images[0]
image_data.shape

torch.Size([3, 32, 32])

In [25]:
type(image_data)

torch.Tensor

In [26]:
image_data

tensor([[[0.8549, 0.7647, 0.6745,  ..., 0.5529, 0.6235, 0.6118],
         [0.6980, 0.6392, 0.5765,  ..., 0.5137, 0.6039, 0.6353],
         [0.5569, 0.5961, 0.5137,  ..., 0.4275, 0.5647, 0.6314],
         ...,
         [0.5490, 0.5255, 0.4745,  ..., 0.3608, 0.3373, 0.5373],
         [0.7137, 0.6824, 0.6706,  ..., 0.4471, 0.4863, 0.4667],
         [0.7569, 0.7098, 0.7373,  ..., 0.6275, 0.5961, 0.4510]],

        [[0.8784, 0.7922, 0.6784,  ..., 0.5569, 0.6314, 0.6235],
         [0.7098, 0.6510, 0.5569,  ..., 0.5216, 0.6039, 0.6275],
         [0.5569, 0.5882, 0.4627,  ..., 0.4392, 0.5569, 0.6039],
         ...,
         [0.4627, 0.4392, 0.3882,  ..., 0.3020, 0.2745, 0.4588],
         [0.6157, 0.5843, 0.5725,  ..., 0.3843, 0.4196, 0.3882],
         [0.6431, 0.5961, 0.6235,  ..., 0.5529, 0.5216, 0.3725]],

        [[0.8706, 0.7804, 0.6667,  ..., 0.4745, 0.5490, 0.5686],
         [0.6745, 0.6196, 0.5373,  ..., 0.4314, 0.5451, 0.5843],
         [0.4980, 0.5333, 0.4431,  ..., 0.3451, 0.5137, 0.

In [27]:
np_image = image_data.numpy()

In [28]:
np_image.shape

(3, 32, 32)

In [29]:
np_image = np.transpose(np_image, (1, 2, 0))

In [30]:
np_image.shape

(32, 32, 3)

In [31]:
plt.figure(figsize = (2, 2))
plt.imshow(np_image)
plt.show()

In [32]:
print(classes[labels[0].item()])

horse


In [33]:
def image_show(image_data, label):
    np_image = image_data.numpy()
    np_image = np.transpose(np_image, (1, 2, 0))
    plt.figure(figsize = (2, 2))
    plt.imshow(np_image)
    plt.title(label)
    plt.show()

In [34]:
image_show(images[1], classes[labels[1].item()])

In [35]:
# First Convolution Layer
class FirstCNN(nn.Module):
    def __init__(self):
        super(FirstCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 5, 3) # (입력 채널의 수, 출력 채널의 수, 커널 사이즈) kernel size 3 => (3, 3)의 matrix

    def forward(self, x):
        y = self.conv1(x)
        return y

In [36]:
cnn = FirstCNN()

In [37]:
out = cnn(images)

In [38]:
print(out.shape)

torch.Size([4, 5, 30, 30])


In [39]:
# (4, 10, 30, 30)
# 4: 이미지의 갯수 batch_size
# 10 : 출력 채널의 수
# (30, 30) : 결과 이미지의 크기
# default padding = (0, 0), stride = (1, 1)

In [40]:
type(out)

torch.Tensor

In [41]:
out.shape

torch.Size([4, 5, 30, 30])

In [42]:
sample = out[0, 0, :, :]
sample.shape

torch.Size([30, 30])

In [43]:
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [44]:
sample = out[0, 1, :, :]
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [45]:
sample = out[0, 4, :, :]
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [46]:
class FirstCNN(nn.Module):
    def __init__(self):
        super(FirstCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 10, 3, 
            padding = (1, 1)
        ) # (입력 채널의 수, 출력 채널의 수, 커널 사이즈) kernel size 3 => (3, 3)의 matrix

    def forward(self, x):
        y = self.conv1(x)
        return y

In [47]:
cnn = FirstCNN()

In [48]:
out = cnn(images)

In [49]:
out.shape

torch.Size([4, 10, 32, 32])

In [50]:
sample = out[0, 0, :, :]
sample.shape

torch.Size([32, 32])

In [51]:
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [52]:
class FirstCNN(nn.Module):
    def __init__(self):
        super(FirstCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 10, 3, 
            # padding = (1, 1),
            stride = (2, 2)
        ) # (입력 채널의 수, 출력 채널의 수, 커널 사이즈) kernel size 3 => (3, 3)의 matrix

    def forward(self, x):
        y = self.conv1(x)
        return y

In [53]:
cnn = FirstCNN()
out = cnn(images)
out.shape

torch.Size([4, 10, 15, 15])

In [54]:
sample = out[0, 0, :, :]
sample.shape


torch.Size([15, 15])

In [55]:
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [56]:
# DeepCNN
class DeepCNN(nn.Module):
    def __init__(self):
        super(DeepCNN, self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 10, 3),
            nn.Conv2d(10, 5, 3)
        )

    def forward(self, x):
        y = self.model(x)
        return y

In [57]:
# DeepCNN 클래스에서
# 1st CNN Layer : Kernel size = (3, 3) | output 채널의 수 = 10 | padding (0, 0) | stride = (1, 1)
# 2st CNN Layer : Kernel size = (3, 3) | output 채널의 수 = 5 | padding (0, 0) | stride = (1, 1)

In [58]:
deep = DeepCNN()
out = deep(images)
print(out.shape)

torch.Size([4, 5, 28, 28])


In [59]:
sample = out[0, 0, :, :]
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [60]:
# PoolingCNN
class avg_pool(nn.Module):
    def __init__(self):
        super(avg_pool, self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 10, 3),
            nn.Conv2d(10, 5, 3),
            nn.AvgPool2d(2, stride = 2)
        )

    def forward(self, x):
        y = self.model(x)
        return y

In [61]:
avg = avg_pool()
out = avg(images)
print(out.shape)

torch.Size([4, 5, 14, 14])


In [62]:
sample = out[0, 0, :, :]
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [63]:
# Max Pool CNN
class max_pool(nn.Module):
    def __init__(self):
        super(max_pool, self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 10, 3),
            nn.Conv2d(10, 5, 3),
            nn.MaxPool2d(2, stride = 2)
        )

    def forward(self, x):
        y = self.model(x)
        return y

In [64]:
max_p = max_pool()
out = max_p(images)
print(out.shape)

torch.Size([4, 5, 14, 14])


In [65]:
sample = out[0, 0, :, :]
plt.figure(figsize = (2, 2))
plt.imshow(sample.detach().numpy())
plt.show()

In [66]:
x = torch.randn(500, 5, 10)
x

tensor([[[-0.1973, -0.7061, -0.0542,  ..., -0.9220, -0.9616,  1.8430],
         [ 1.8451, -0.1032, -1.1835,  ..., -2.5936, -0.9152, -0.6460],
         [-0.1354,  0.1815, -1.4497,  ...,  0.5736,  0.6619,  2.0763],
         [-0.1157,  0.8591,  0.7713,  ...,  2.1441,  1.1046,  1.2000],
         [-0.9197, -0.2649, -0.6238,  ...,  0.0696, -1.0107, -1.1691]],

        [[-0.6029,  1.6478, -1.4422,  ..., -0.5007,  0.9802, -1.2160],
         [-0.8710, -1.3343,  0.5929,  ..., -1.5177,  1.5487,  1.7732],
         [-1.0905,  0.4040,  1.0669,  ..., -1.0373, -0.0651,  1.0246],
         [-0.4822,  0.7561,  0.6301,  ..., -0.6199,  0.4203, -0.9041],
         [ 2.4305,  0.0772, -0.2567,  ...,  0.1744, -0.3325,  0.3803]],

        [[-0.6330,  0.7665, -0.9902,  ..., -0.2284, -1.0260,  0.6020],
         [ 0.7665, -0.2113, -0.4357,  ..., -0.5816,  0.9237,  0.1411],
         [ 0.3198, -0.4730, -0.2941,  ...,  0.6804, -0.1432,  0.7041],
         [-0.3422,  1.4484, -0.1046,  ..., -0.7255,  2.4459,  0.7640],
  

In [67]:
x = torch.flatten(x)
x.shape

torch.Size([25000])

In [68]:
x

tensor([-0.1973, -0.7061, -0.0542,  ...,  1.9645,  1.1969,  0.9848])

In [69]:
x = torch.randn(500, 5, 10)
x = torch.flatten(x, 1)
x, x.shape

(tensor([[-0.1484, -1.2934,  0.4788,  ...,  2.0988,  0.4398, -0.8131],
         [-0.5530,  0.3805, -0.8099,  ...,  1.3926,  0.8337,  0.0306],
         [-0.6351,  0.3708, -0.0352,  ..., -0.4384, -0.1418,  1.9801],
         ...,
         [ 0.6648,  1.1565, -0.9017,  ..., -0.7421,  0.8320,  1.7531],
         [-1.4427,  0.1126, -1.0231,  ..., -0.3694,  1.5076,  0.4769],
         [ 0.6070, -0.9259,  0.2712,  ..., -0.5218, -2.6328, -1.4084]]),
 torch.Size([500, 50]))

In [70]:
class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv_model = nn.Sequential(
            nn.Conv2d(3,6,5),
            nn.Tanh(),
            nn.AvgPool2d(2, stride=2),
            nn.Conv2d(6, 16, 5),
            nn.Tanh(),
            nn.AvgPool2d(2, stride=2)
        )

        self.dense_model = nn.Sequential(
            nn.Linear(400, 120),
            nn.Tanh(),
            nn.Linear(120, 84),
            nn.Tanh(),
            nn.Linear(84, 10)

        )

    def forward(self, x):
        y = self.conv_model(x)
        y = torch.flatten(y, 1)
        y = self.dense_model(y)
        return y

In [71]:
net = LeNet()
out = net(images)

In [72]:
out.shape

torch.Size([4, 10])

In [73]:
out

tensor([[-0.1207, -0.1186,  0.0047, -0.0199, -0.1331,  0.0983, -0.1083,  0.0171,
         -0.0047,  0.0509],
        [-0.1390, -0.1154, -0.0036, -0.0250, -0.1225,  0.1047, -0.1141,  0.0036,
         -0.0023,  0.0663],
        [-0.1221, -0.1199,  0.0019, -0.0212, -0.1292,  0.1042, -0.1173,  0.0180,
         -0.0133,  0.0624],
        [-0.1410, -0.1179, -0.0007, -0.0196, -0.1263,  0.0921, -0.1106,  0.0162,
          0.0100,  0.0559]], grad_fn=<AddmmBackward>)

In [74]:
torch.max(out)

tensor(0.1047, grad_fn=<MaxBackward1>)

In [75]:
torch.max(out, dim = 1)

torch.return_types.max(
values=tensor([0.0983, 0.1047, 0.1042, 0.0921], grad_fn=<MaxBackward0>),
indices=tensor([5, 5, 5, 5]))

In [76]:
max_values, predict_class = torch.max(out, dim = 1)

In [77]:
max_values, predict_class

(tensor([0.0983, 0.1047, 0.1042, 0.0921], grad_fn=<MaxBackward0>),
 tensor([5, 5, 5, 5]))

In [78]:
batch_size = 256

In [79]:
net = LeNet()