neural_network_study.ipynb

In [1]:
import torch
import torch.nn as nn

In [2]:
n_in, n_h, n_out, batch_size = 10, 5, 1, 10

In [3]:
x = torch.randn(batch_size, n_in)
y = torch.tensor([ [1.], [1.], [0.], [1.], [0.], [1.], [0.], [1.], [1.], [0.] ])
x, y

(tensor([[ 0.5438,  0.7618,  2.7988, -0.4246, -0.8549,  0.3536,  1.0075,  0.7067,
          -0.7033,  0.8669],
         [ 0.6087, -0.3894, -0.4958, -0.6928,  0.5338, -0.5139, -1.4149, -1.2338,
           0.4246,  0.0633],
         [-0.3636,  0.0657,  1.1368,  1.9268, -0.4148,  0.4798,  0.5540,  1.9926,
          -1.2777, -2.6687],
         [-0.9780, -1.1629, -1.9202, -1.6580,  0.3696, -0.4899,  0.2291, -1.0204,
           1.8573, -0.0234],
         [-0.3130, -1.0038, -1.2396,  0.8708, -0.9561, -1.2947, -0.9094, -0.5862,
          -1.3043, -0.3365],
         [-0.0107,  0.0763,  0.6213,  1.2972, -1.1637,  1.2142,  1.5342,  0.1677,
          -0.5744,  0.3541],
         [-2.3239, -0.8488, -0.4629, -0.9441,  1.0011, -0.4377,  2.1793, -2.0460,
          -0.3604, -0.3297],
         [ 0.8936,  0.3977,  1.2376,  0.6749,  1.0424,  0.0615, -0.4844, -1.7592,
           1.0900,  0.6621],
         [ 0.1590,  0.2590, -0.4724, -0.0984,  0.6236,  0.6847,  0.4409, -0.2471,
          -0.3004,  0.6149],
 

In [6]:
model = nn.Sequential(
    nn.Linear(n_in, n_h),
    nn.ReLU(),
    nn.Linear(n_h, n_out),
    nn.Sigmoid()
)

In [7]:
loss_func = nn.MSELoss()

In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


In [13]:
for i in range(2500):
    y_pred = model(x)
    loss = loss_func(y_pred, y)

    print('epoch : ', (i + 1), "loss : ", loss.item())
    loss.backward() # 역전파 적용

    optimizer.step() # 모든 파라미터 최신화

    optimizer.zero_grad()

 :  0.0160058606415987
epoch :  2034 loss :  0.01599273458123207
epoch :  2035 loss :  0.015979718416929245
epoch :  2036 loss :  0.015967048704624176
epoch :  2037 loss :  0.01595389097929001
epoch :  2038 loss :  0.015941187739372253
epoch :  2039 loss :  0.01592833921313286
epoch :  2040 loss :  0.01591542549431324
epoch :  2041 loss :  0.015902459621429443
epoch :  2042 loss :  0.015889693051576614
epoch :  2043 loss :  0.015877094119787216
epoch :  2044 loss :  0.015863917768001556
epoch :  2045 loss :  0.015851283445954323
epoch :  2046 loss :  0.015838731080293655
epoch :  2047 loss :  0.015825703740119934
epoch :  2048 loss :  0.01581278070807457
epoch :  2049 loss :  0.015800392255187035
epoch :  2050 loss :  0.01578766480088234
epoch :  2051 loss :  0.015774598345160484
epoch :  2052 loss :  0.01576211303472519
epoch :  2053 loss :  0.01574987918138504
epoch :  2054 loss :  0.01573674939572811
epoch :  2055 loss :  0.01572389528155327
epoch :  2056 loss :  0.01571194641292095

## torch.nn.module을 사용해서 많은 간단한 레이어를 복잡한 뉴럴 네트워크로 만들 수 있다.

In [17]:
class Custom_class(nn.Module):
    def __init__(self, n_in, n_h, n_out):
        super(Custom_class, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(n_in, n_h),
            nn.ReLU(),
            nn.Linear(n_h, n_out),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [18]:
custom_nn = Custom_class(n_in, n_h, n_out)

In [19]:
loss_func = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


In [20]:
for i in range(2500):
    y_pred = model(x)
    loss = loss_func(y_pred, y)

    print('epoch : ', (i + 1), "loss : ", loss.item())
    loss.backward() # 역전파 적용

    optimizer.step() # 모든 파라미터 최신화

    optimizer.zero_grad()

0.003916525281965733
epoch :  2042 loss :  0.003915096633136272
epoch :  2043 loss :  0.00391352828592062
epoch :  2044 loss :  0.003912078682333231
epoch :  2045 loss :  0.0039106192998588085
epoch :  2046 loss :  0.00390907097607851
epoch :  2047 loss :  0.0039076171815395355
epoch :  2048 loss :  0.0039061219431459904
epoch :  2049 loss :  0.003904605284333229
epoch :  2050 loss :  0.003903129370883107
epoch :  2051 loss :  0.0039016064256429672
epoch :  2052 loss :  0.003900171723216772
epoch :  2053 loss :  0.0038986620493233204
epoch :  2054 loss :  0.003897163551300764
epoch :  2055 loss :  0.0038957339711487293
epoch :  2056 loss :  0.0038941637612879276
epoch :  2057 loss :  0.0038927230052649975
epoch :  2058 loss :  0.0038912673480808735
epoch :  2059 loss :  0.0038897048216313124
epoch :  2060 loss :  0.0038883157540112734
epoch :  2061 loss :  0.0038868163246661425
epoch :  2062 loss :  0.0038853385485708714
epoch :  2063 loss :  0.0038838591426610947
epoch :  2064 loss : 

In [21]:
import torch
import torch.optim as optim
import torch.nn as nn

# torch.nn : neural network를 만드는데 꼭 필요한 모듈이다.

In [22]:
import numpy as np
import matplotlib.pyplot as plt


In [23]:
class EgLayer(nn.Module):
    def __init__(self, param):
        super().__init__()
        self.param = param

    def forward(self, x):
        return x * self.param

myOb = EgLayer(8)
output = myOb(torch.Tensor([1, 2, 3]))
print(output)


tensor([ 8., 16., 24.])


In [24]:
n_in, n_h, n_out = 6, 4, 1


In [26]:
x = torch.randn((1, n_in))
y = torch.randn((1, n_out))
x, y

(tensor([[-1.0388, -1.4482,  0.0329, -0.2891,  2.3674, -1.4050]]),
 tensor([[-1.1167]]))

In [27]:
b1 = torch.randn((1, n_h))
b2 = torch.randn((1, n_out))
b1, b2

(tensor([[-1.3527, -0.0236,  0.1597,  1.1823]]), tensor([[0.9111]]))

In [30]:
w1 = torch.randn(n_in, n_h)
w2 = torch.randn(n_h, n_out)
w1, w2

(tensor([[ 0.6835,  1.1333,  0.9484,  0.5462],
         [ 0.6131, -0.4834,  1.2760,  0.6268],
         [ 0.0481, -0.2843,  1.0128,  0.1890],
         [-0.0193,  1.0166, -0.0788, -0.8266],
         [ 0.3201,  0.8299,  1.1345, -1.1021],
         [-0.5183, -0.5655, -1.4727, -0.9215]]),
 tensor([[ 0.6082],
         [-2.8289],
         [-1.2786],
         [-0.9487]]))

In [28]:
def sigmoid_activation(z):
    return 1 / (1+torch.exp(-z))
    

In [31]:
z1 = torch.mm(x, w1) + b1
a1 = sigmoid_activation(z1)

In [32]:
z2 = torch.mm(a1, w2) + b2
output = sigmoid_activation(z2)

In [33]:
loss = y - output

In [34]:
def sigmoid_delta(x):
    return x * (1 - x)

In [35]:
delta_out = sigmoid_delta(output)
delta_h = sigmoid_delta(a1)


In [36]:
d_outp = loss * delta_out
loss_h = torch.mm(d_outp, w2.t())
d_hidn = loss_h * delta_h
