In [1]:
## pytorch_study.ipynb

In [6]:
import torch
import numpy as np

In [4]:
list1 = ([1, 2], [3, 4])


In [5]:
type(list1)

tuple

In [7]:
example_tensor =torch.tensor(list1)

In [8]:
example_tensor

tensor([[1, 2],
        [3, 4]])

In [9]:
type(example_tensor)

torch.Tensor

In [10]:
list2 = [1,2,3,4,5]

In [11]:
type(list2)

list

In [12]:
example_tensor = torch.tensor(list2)

In [13]:
example_tensor

tensor([1, 2, 3, 4, 5])

In [14]:
type(example_tensor)

torch.Tensor

In [17]:
np_tensor = torch.tensor(np.array([1,2,3,4,5,6]))


In [18]:
np_tensor

tensor([1, 2, 3, 4, 5, 6])

In [19]:
type(np_tensor)

torch.Tensor

In [20]:
example_tensor = torch.tensor(1)

In [21]:
example_tensor

tensor(1)

In [22]:
type(example_tensor)

torch.Tensor

In [23]:
# 비어있는 텐서
empty_tensor = torch.tensor([])

In [24]:
empty_tensor


tensor([])

In [25]:
tensor_float = torch.tensor([3,4,5], dtype= torch.float32)


In [26]:
tensor_float


tensor([3., 4., 5.])

In [30]:
tensor_int = torch.tensor([3,4,5], dtype=torch.int32)


In [33]:
tensor_int

tensor([3, 4, 5], dtype=torch.int32)

In [34]:
tensor_float.dtype, tensor_int.dtype

(torch.float32, torch.int32)

In [38]:
x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [39]:
x_zero = torch.zeros(3,3)
print(x_zero)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [43]:
# 0 ~ 1 사이의 임의의 값
torch.rand(4,2)

tensor([[0.5277, 0.5883],
        [0.1892, 0.7177],
        [0.9175, 0.3627],
        [0.4546, 0.0950]])

In [44]:
y = torch.arange(10)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
torch.arange(5,10)


tensor([5, 6, 7, 8, 9])

In [46]:
torch.arange(5, 50, 5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [48]:
torch.linspace(0, 50, 5)

tensor([ 0.0000, 12.5000, 25.0000, 37.5000, 50.0000])

In [50]:
torch.empty(3, 3)

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00],
        [-2.0000e+00,  9.8091e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [52]:
torch.empty(3, 3).dtype

torch.float32

In [54]:
# identity matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [56]:
torch.full((3, 4), 5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [57]:
torch.full((3, 4), 5).dtype


torch.int64

In [63]:
new_tensor = torch.arange(9)
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
new_tensor.shape

torch.Size([9])

In [66]:
new_tensor.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [67]:
new_tensor = torch.arange(8)
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
new_tensor.view(2, 4)


tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [69]:
new_tensor.reshape(2,4)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

### tensor.view : contiguous tensor에만 적용 가능, 메모리에 적용되지 않음 (완전 view용)
### tensor.reshape : 어떤 tensor에도 가능, 메모리에 적용함

In [71]:
x = torch.arange(8).reshape(4, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

The history saving thread hit an unexpected error (OperationalError('unable to open database file')).History will not be written to the database.


In [72]:
x[2,1]

tensor(5)

In [73]:
x[2, 1].item()

5

In [74]:
type(x[2, 1].item())


int

In [80]:
x[:, 1].item()


ValueError: only one element tensors can be converted to Python scalars

In [81]:
x[2,:]

tensor([4, 5])

In [82]:
x = torch.ones(3, 2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [88]:
y = torch.full((3, 2), 3.)
y

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [89]:
print(f"덧셈 : {x + y}")
print(f"뺄셈 : {x - y}")
print(f"곱셈 : {x * y}")
print(f"나눗셈 : {x / y}")


덧셈 : tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
뺄셈 : tensor([[-2., -2.],
        [-2., -2.],
        [-2., -2.]])
곱셈 : tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
나눗셈 : tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])


In [96]:
z = x.add(y)
z

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]])

In [98]:
y

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])

In [99]:
z = y.add_(x) # add()와 add_() 차이
z

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]])

In [103]:
x.mul(y)

tensor([[216., 216.],
        [216., 216.],
        [216., 216.]])

In [105]:
x.mul_(y)

tensor([[1296., 1296.],
        [1296., 1296.],
        [1296., 1296.]])

In [113]:
x = torch.tensor(np.array([1,2,3,4,5,6,7]))
type(x), x

(torch.Tensor, tensor([1, 2, 3, 4, 5, 6, 7]))

In [114]:
x = x.numpy()
type(x), x

(numpy.ndarray, array([1, 2, 3, 4, 5, 6, 7]))

In [116]:
z = torch.from_numpy(x)
type(z), z

(torch.Tensor, tensor([1, 2, 3, 4, 5, 6, 7]))

In [117]:
z[0] = -10
z

tensor([-10,   2,   3,   4,   5,   6,   7])

In [118]:
x

array([-10,   2,   3,   4,   5,   6,   7])

In [119]:
z[5] = 100
z

tensor([-10,   2,   3,   4,   5, 100,   7])

In [120]:
x

array([-10,   2,   3,   4,   5, 100,   7])

In [122]:
%%time
for i in range(100000):
    x = np.random.randn(100, 100)
    y = np.random.randn(100, 100)
    z = x + y


CPU times: user 1min 52s, sys: 2.55 s, total: 1min 54s
Wall time: 2min 4s


In [123]:
%%time
for i in range(100000):
    x = torch.randn(100, 100)
    y = torch.randn(100, 100)
    z = x + y


CPU times: user 27.3 s, sys: 832 ms, total: 28.1 s
Wall time: 30 s


In [124]:
%%time
for i in range(100000):
    x = np.random.randn(100, 100)
    y = np.random.randn(100, 100)
    z = np.matmul(x, y)


CPU times: user 5min 13s, sys: 1min 35s, total: 6min 49s
Wall time: 2min 35s


In [125]:
%%time
for i in range(100000):
    x = torch.randn(100, 100)
    y = torch.randn(100, 100)
    z = torch.matmul(x, y)


CPU times: user 28.3 s, sys: 740 ms, total: 29.1 s
Wall time: 30.2 s
